/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeaderIndex: typeof import('./src/components/headerIndex.vue')['default']
    LogoShop: typeof import('./src/components/tools/LogoShop.vue')['default']
    OrderShop: typeof import('./src/components/tools/orderShop.vue')['default']
    PartnerShopHeader: typeof import('./src/components/PartnerShopHeader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMenuShop: typeof import('./src/components/tools/UserMenuShop.vue')['default']
  }
}
