// import './example/1_basic-type.ts'
// import './example/2_sumbol'
// import './example/3_interface'
// import './example/4_function'
// import './example/5_generics'
// import './example/6_es6-class-1'
// import './example/7_es6-class-2'
import './example/8_class'
