// import './example/1_basic-type.ts'
// import './example/2_symbol'
// import './example/3_interface'
// import './example/4_function'
// import './example/5_generics'
// import './example/6_es6-class-1'
// import './example/7_es6-class-2'
// import './example/8_class'
// import './example/9_enum'
// import './example/10_类型推断'
// import './example/11_高级类型(1)'
import './example/12_高级类型(2)'
